/**
 * Operational Language Copy System
 * Replaces generic loading/status text with professional ops language
 */

export const OPS_STATUS = {
  // General loading states
  LOADING_DATA: 'RETRIEVING DATA...',
  LOADING_ROSTER: 'ASSEMBLING ROSTER...',
  LOADING_COMMS: 'TUNING FREQUENCIES...',
  LOADING_ASSETS: 'CATALOGING ASSETS...',
  LOADING_EVENTS: 'RETRIEVING OPERATIONS...',
  
  // Comms-specific
  PROVISIONING_NETS: 'PROVISIONING NETS...',
  CONNECTING_VOICE: 'ESTABLISHING VOICE LINK...',
  SYNCING_CHANNEL: 'SYNCHRONIZING CHANNEL...',
  AWAITING_QUORUM: 'AWAITING QUORUM...',
  
  // Event-specific
  CREATING_EVENT: 'INITIALIZING OPERATION...',
  UPDATING_EVENT: 'UPDATING OPERATION PARAMETERS...',
  PROVISIONING_EVENT: 'PROVISIONING EVENT INFRASTRUCTURE...',
  STANDING_BY: 'STANDING BY...',
  
  // Roster/presence
  UPDATING_PRESENCE: 'UPDATING PRESENCE...',
  REGISTERING_PARTICIPANT: 'REGISTERING PARTICIPANT...',
  
  // Analysis/AI
  ANALYZING: 'ANALYZING SITUATION...',
  GENERATING_REPORT: 'GENERATING REPORT...',
  CONSULTING_AI: 'CONSULTING AI ADVISOR...',
  PROCESSING: 'PROCESSING...',
  
  // Archive/search
  SEARCHING_ARCHIVE: 'SEARCHING ARCHIVE...',
  RETRIEVING_HISTORY: 'RETRIEVING HISTORY...',
  
  // Error states
  CONNECTION_LOST: 'COMMS LOST - RETRYING...',
  FAILED_TO_LOAD: 'FAILED TO RETRIEVE DATA',
  OPERATION_FAILED: 'OPERATION FAILED',
  AUTHORIZATION_REQUIRED: 'AUTHORIZATION REQUIRED',
  
  // Success states
  OPERATION_COMPLETE: 'OPERATION COMPLETE',
  SAVED: 'SAVED',
  RECORDED: 'RECORDED',
  TRANSMITTED: 'TRANSMITTED',
  CONFIRMED: 'CONFIRMED',
  
  // Empty states
  NO_OPERATIONS: 'NO SCHEDULED OPERATIONS',
  NO_ACTIVE_NETS: 'NO ACTIVE NETS',
  NO_DATA: 'NO DATA AVAILABLE',
  NO_RESULTS: 'NO RESULTS FOUND',
  
  // Time-based contextual
  AWAITING_START: 'AWAITING OPERATION START...',
  OPERATION_ACTIVE: 'OPERATION ACTIVE',
  OPERATION_COMPLETED: 'OPERATION COMPLETED',
  OPERATION_CANCELLED: 'OPERATION CANCELLED'
};

/**
 * Returns contextual loading text based on current operation
 */
export function getOperationalStatus(context) {
  const contextMap = {
    'events': OPS_STATUS.LOADING_EVENTS,
    'comms': OPS_STATUS.TUNING_FREQUENCIES,
    'roster': OPS_STATUS.ASSEMBLING_ROSTER,
    'assets': OPS_STATUS.CATALOGING_ASSETS,
    'ai': OPS_STATUS.CONSULTING_AI,
    'archive': OPS_STATUS.SEARCHING_ARCHIVE,
    'presence': OPS_STATUS.UPDATING_PRESENCE,
    'voice': OPS_STATUS.ESTABLISHING_VOICE_LINK
  };

  return contextMap[context] || OPS_STATUS.PROCESSING;
}

/**
 * Returns contextual error text
 */
export function getOperationalError(context) {
  if (context === 'connection') return OPS_STATUS.CONNECTION_LOST;
  if (context === 'auth') return OPS_STATUS.AUTHORIZATION_REQUIRED;
  return OPS_STATUS.OPERATION_FAILED;
}