export const PERMISSIONS = {
  // Administrative
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_ADMIN_PANEL: "VIEW_ADMIN_PANEL",

  // Comms / Nets
  MANAGE_NETS: "MANAGE_NETS",
  TRANSMIT_AUDIO: "TRANSMIT_AUDIO",
  LISTEN_AUDIO: "LISTEN_AUDIO",
  VIEW_COMMS_LOGS: "VIEW_COMMS_LOGS",

  // Operations
  CREATE_EVENT: "CREATE_EVENT",
  MANAGE_EVENT: "MANAGE_EVENT",
  VIEW_TACTICAL_MAP: "VIEW_TACTICAL_MAP",

  // Assets
  MANAGE_ARMORY: "MANAGE_ARMORY",
  MANAGE_TREASURY: "MANAGE_TREASURY",
};

export const PERMISSION_LABELS = {
  [PERMISSIONS.MANAGE_ROLES]: "Manage Roles & Permissions",
  [PERMISSIONS.MANAGE_USERS]: "Manage Users",
  [PERMISSIONS.VIEW_ADMIN_PANEL]: "Access Admin Panel",
  [PERMISSIONS.MANAGE_NETS]: "Create/Edit Voice Nets",
  [PERMISSIONS.TRANSMIT_AUDIO]: "Transmit on Nets",
  [PERMISSIONS.LISTEN_AUDIO]: "Listen to Nets",
  [PERMISSIONS.VIEW_COMMS_LOGS]: "View Comms Logs",
  [PERMISSIONS.CREATE_EVENT]: "Create Operations/Events",
  [PERMISSIONS.MANAGE_EVENT]: "Manage Active Operations",
  [PERMISSIONS.VIEW_TACTICAL_MAP]: "View Tactical Map",
  [PERMISSIONS.MANAGE_ARMORY]: "Manage Armory/Inventory",
  [PERMISSIONS.MANAGE_TREASURY]: "Manage Treasury/Coffers",
};